name: CPULLVM Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_DEFCONFIG: "star2qlte_chn_open_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 O=out LLVM=1"
      EXTRAVERSION: "-RelDEV"
    
    steps:
#      - name: Cleanup
#        uses: rokibhasansagar/slimhub_actions@main

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 24

      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: Andrey0800770/samsung_sdm845-kernel
          ref: dev
          submodules: "false"
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sed -i 's/EXTRAVERSION =.*/EXTRAVERSION = ${{ env.EXTRAVERSION }}/' Makefile
          sudo apt-get update -y 
          sudo apt-get install -y --no-install-recommends libc6-dev linux-libc-dev pixz aria2 binutils make python3 libssl-dev build-essential bc bison flex unzip ca-certificates xz-utils mkbootimg cpio device-tree-compiler git
          aria2c -x16 -s16 -k1M https://github.com/qualcomm/cpullvm-toolchain/releases/download/cpullvm-22.1.1/cpullvm-22.1.1-Linux-x86_64.tar.xz
          mkdir clang
          tar -I pixz -xf cpullvm-*.tar.xz -C clang || tar -xf cpullvm-*.tar.xz -C clang
          mv clang/cpullvm* clang/clang
          git clone --depth=1 https://github.com/Andrey0800770/kernel-build/ -b anykernel AnyKernel3 && rm -rf AnyKernel3/.git*
      - name: Build Kernel
        run: |
          export PATH=$(pwd)/clang/clang/bin/:$PATH
          which clang
          clang --version
          echo | clang -E -x c - -v
          export KBUILD_BUILD_USER="andrey" KBUILD_BUILD_HOST="linux"
          make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="clang" HOSTCC="clang --target=x86_64-linux-gnu" HOSTCXX="clang++ --target=x86_64-linux-gnu"
          make $KERNEL_CMDLINE CC="clang" HOSTCC="clang --target=x86_64-linux-gnu" HOSTCXX="clang++ --target=x86_64-linux-gnu" -j$(nproc --all)
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3
      - name: Upload Kernel
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.KERNEL_DEFCONFIG }}-${{ github.run_number }}
          path: "AnyKernel3/*"
