name: Gcc-Arm
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "4G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "star2qlte_chn_open_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 O=out CLANG_TRIPLE=aarch64-none-linux-gnu- CROSS_COMPILE=aarch64-none-linux-gnu- CROSS_COMPILE_ARM32=arm-none-linux-gnueabihf- CROSS_COMPILE_COMPAT=arm-none-linux-gnueabihf-"
      EXTRAVERSION: "-dev"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: Andrey0800770/samsung_sdm845-kernel
          ref: dev
          submodules: "false"
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sed -i 's/EXTRAVERSION =.*/EXTRAVERSION = ${{ env.EXTRAVERSION }}/' Makefile
          sudo apt-get update -y 
          sudo apt install aria2 binutils make python3 libssl-dev build-essential bc bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
          aria2c -j$(nproc --all) -o gcc32.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-linux-gnueabihf.tar.xz && tar -xJf gcc32.tar.xz
          aria2c -j$(nproc --all) -o gcc.tar.xz https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz && tar -xJf gcc.tar.xz
          git clone --depth=1 https://github.com/Andrey0800770/kernel-build/ -b anykernel AnyKernel3 && rm -rf AnyKernel3/.git*
          ls $(pwd)/
          ls $(pwd)/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin
          ls $(pwd)/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-linux-gnueabihf/bin
      - name: Build Kernel-With-KernelSU
        run: |
          export PATH=$(pwd)/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin/:$(pwd)/arm-gnu-toolchain-14.2.rel1-x86_64-arm-none-linux-gnueabihf/bin:$PATH
          make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="gcc"
          make $KERNEL_CMDLINE CC="gcc" -j$(nproc --all)
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3
      - name: Upload Kernel
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.KERNEL_DEFCONFIG }}
          path: "AnyKernel3/*"
