name: GCC EVA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "4G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "star2qlte_chn_open_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 O=out CLANG_TRIPLE=aarch64-elf- CROSS_COMPILE=aarch64-elf- CROSS_COMPILE_ARM32=arm-eabi- CROSS_COMPILE_COMPAT=arm-eabi-"
      EXTRAVERSION: "-dev"
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: Andrey0800770/samsung_sdm845-kernel
          ref: dev
          submodules: "false"
          fetch-depth: 1

      - name: Install dependencies
        run: |
          sed -i 's/EXTRAVERSION =.*/EXTRAVERSION = ${{ env.EXTRAVERSION }}/' Makefile
          sudo apt-get update -y 
          sudo apt install aria2 binutils make python3 libssl-dev build-essential bc bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
          aria2c -j$(nproc --all) -o gcc32.xz https://github.com/mvaisakh/gcc-build/releases/download/31052026/eva-gcc-arm-31052026.xz && xz -d -T0 gcc32.xz
          aria2c -j$(nproc --all) -o gcc.xz https://github.com/mvaisakh/gcc-build/releases/download/31052026/eva-gcc-arm64-31052026.xz && xz -d -T0 gcc.xz
          git clone --depth=1 https://github.com/Andrey0800770/kernel-build/ -b anykernel AnyKernel3 && rm -rf AnyKernel3/.git*
      - name: Build Kernel-With-KernelSU
        run: |
          export PATH=$(pwd)/gcc-arm64/bin/:$(pwd)/gcc-arm/bin:$PATH
          make $KERNEL_CMDLINE $KERNEL_DEFCONFIG
          make $KERNEL_CMDLINE -j$(nproc --all)
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3
      - name: Upload Kernel
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.KERNEL_DEFCONFIG }}
          path: "AnyKernel3/*"
