name: LLVM Build
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: star2qlte_chn_open_defconfig
          arch: arm64
          clang-url: https://gitlab.com/ZyCromerZ/sdclang-16.1.0.1.git
          path: $CLANG:$GCC64:$PATH
          cflags: "CROSS_COMPILE=aarch64-linux-gnu- CC=clang LD=ld.lld AS=aarch64-linux-gnu-as"
          python: python2
          anykernel3: true
