name: LLVM Clang
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KERNEL_DEFCONFIG: "star2qlte_chn_open_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 O=out LLVM=1 LD_LIBRARY_PATH=/usr/lib/llvm-22/lib/"
      EXTRAVERSION: "-RelDEV"
      
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          repository: Andrey0800770/samsung_sdm845-kernel
          ref: dev
          submodules: "false"
          fetch-depth: 1

#      - name: Set up ccache
#        uses: hendrikmuhs/ccache-action@v1.2

      - name: Install dependencies
        run: |
          sed -i 's/EXTRAVERSION =.*/EXTRAVERSION = ${{ env.EXTRAVERSION }}/' Makefile
          sudo tee /etc/apt/sources.list > /dev/null <<EOF
          deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
          EOF
          sudo apt-get update -y 
          sudo dpkg -l | grep clang | awk '{print $2}' | xargs sudo apt-get remove -y
          wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 22
          curl -L -o register_clang.sh https://raw.githubusercontent.com/Andrey0800770/kernel-build/main/files/update-alternatives.sh && chmod +x register_clang.sh && sudo bash -c 'set +e; for tool in clang++ clang-format clang-cpp clang-cl clangd clang-tidy clang-check clang-query asan_symbolize bugpoint dsymutil lld ld.lld lld-link llc lli obj2yaml opt sanstats verify-uselistorder wasm-ld yaml2obj; do update-alternatives --query $tool >/dev/null 2>&1 && update-alternatives --remove $tool /usr/bin/$tool-22 || true; done; ./register_clang.sh 22 1000 || true'
          git clone --depth=1 https://github.com/Andrey0800770/kernel-build/ -b anykernel AnyKernel3 && rm -rf AnyKernel3/.git*
      - name: Build Kernel-With-KernelSU
        run: |
          make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="clang"
          make $KERNEL_CMDLINE CC="clang" -j$(nproc --all)
          cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3
      - name: Upload Kernel
        uses: actions/upload-artifact@v5
        with:
          name: ${{ env.KERNEL_DEFCONFIG }}-${{ github.run_number }}
          path: "AnyKernel3/*"
