name: dev
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: dev
          config: star2qlte_chn_open_defconfig
          arch: arm64
          gcc64-tar: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/98d3c628eaa366985d4212905bfdb35a47962e37/clang-r547379.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true
