name: LLVM Build
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: star2qlte_chn_open_defconfig
          arch: arm64
          clang-url: https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86 -b clang-r536225
          path: $CLANG:$PATH
          make-options: "make CC=clang -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- O=out ARCH=arm64"
          python: python2
          anykernel3: true
