# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    runs-on: ubuntu-latest
    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@v1.7.0
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-branch: main
          config: star2qlte_chn_open_defconfig
          arch: arm64
          aosp-gcc: true
          android-version: 10
