name: Compile all devices

on: [push]

jobs:
  run-multiple-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Run crownqltechn workflow
        uses: ./.github/workflows/devices/crownqltechn.yml

    
