name: Compile all devices

on: [push]

jobs:
  run-multiple-actions:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório para garantir que os arquivos estejam disponíveis
      - name: Checkout repository
        uses: actions/checkout@v2

      # Executa a primeira ação
      - name: Run action 1
        uses: ./.github/actions/devices/star2qltechn.yml

      # Executa a segunda ação
      - name: Run action 2
        uses: ./.github/actions/devices/starqltechn.yml

      # Executa a terceira ação
      - name: Run action 3
        uses: ./.github/actions/devices/star2qlte.yml

      # Executa a quarta ação
      - name: Run action 4
        uses: ./.github/actions/devices/starqlte.yml

      # Executa a quinta ação
      - name: Run action 5
        uses: ./.github/actions/devices/crownqltechn.yml
