name: Run Multiple Actions

on: [push, workflow_dispatch]

jobs:
  job1:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run action 1
        uses: ./github/actions/star2qltechn
        with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: star2qlte_chn_open_defconfig
          arch: arm64
          clang-tar: https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250103-release/Clang-20.0.0git-20250103.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true

  job2:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run action 2
        uses: ./github/actions/starqltechn
        with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: starqlte_chn_open_defconfig
          arch: arm64
          clang-tar: https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250103-release/Clang-20.0.0git-20250103.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true

  job3:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run action 3
        uses: ./github/actions/star2qlte
        with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: star2qlte_chn_open_defconfig
          arch: arm64
          clang-tar: https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250103-release/Clang-20.0.0git-20250103.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true

  job4:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run action 4
        uses: ./github/actions/starqlte
        with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: starqlte_usa_single_defconfig
          arch: arm64
          clang-tar: https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250103-release/Clang-20.0.0git-20250103.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true

  job5:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run action 5
        uses: ./github/actions/crownqltechn
        with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: ksu+susfs
          config: crownqlte_chn_open_defconfig
          arch: arm64
          clang-tar: https://github.com/ZyCromerZ/Clang/releases/download/20.0.0git-20250103-release/Clang-20.0.0git-20250103.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
          python: python2
          anykernel3: true
