name: Build SM64 Android⁷
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download and extract baserom
        run: |
          wget -O Super_Mario_64_USA.zip https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20%28BigEndian%29/Super%20Mario%2064%20%28USA%29.zip
          unzip Super_Mario_64_USA.zip
          mv "Super Mario 64 (USA).z64" app/jni/src/baserom.us.z64

      - name: Build Docker image
        run: docker build . -t sm64_android

      - name: Set up SDL symlinks
        run: |
          docker run --rm -v $(pwd):/sm64 sm64_android sh -c "ln -nsf /SDL2-2.0.12/src /sm64/app/jni/SDL/src"
          docker run --rm -v $(pwd):/sm64 sm64_android sh -c "ln -nsf /SDL2-2.0.12/include /sm64/app/jni/SDL/include"

      - name: Perform native build
        run: docker run --rm -v $(pwd):/sm64 sm64_android sh -c "cd /sm64/app/jni/src && make --jobs 4"

      - name: Perform Android build
        run: docker run --rm -v $(pwd):/sm64 sm64_android sh -c "./gradlew assembleDebug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: sm64_android_apk
          path: app/build/outputs/apk/debug/app-debug.apk
