name: Update Cache

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set-up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: kernel/sdm845
        key: main-160225
        restore-keys: |
          main

    - name: Downloading kernel
      if: steps.kernel-cache.outputs.cache-hit
      run: |
        rm -rf kernel/sdm845
        git clone --recursive https://github.com/Andrey0800770/samsung_sdm845-kernel -b main kernel/sdm845  
               
    - name: Set-Up clang cache
      id: clang-cache
      uses: actions/cache@v4.2.0
      with:
        path: /home/runner/clang
        key: clang-r547379
        restore-keys: |
          clang-r547379"
