name: Update Cache

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set-up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: kernel/sdm845
        key: main-${{ github.run_id }}
        restore-keys: |
          main

    - name: Downloading kernel
      if: steps.kernel-cache.outputs.cache-hit != 'true'
      run: |
        rm -rf kernel/sdm845
        git clone --branch main https://github.com/Andrey0800770/samsung_sdm845-kernel kernel/sdm845        
        
    - name: Set-Up clang cache
      id: clang-cache
      uses: actions/cache@v4.2.0
      with:
        path: /home/runner/clang
        key: clang-r547379-${{ github.run_id }}
        restore-keys: |
          clang-r547379
      
    - name: Downloading and extracting Clang
      if: steps.clang-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /home/runner/clang
        curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/d19c99c180cfa21504426915d765b5e7adf878b6/clang-r547379.tar.gz -o "clang.tar" && tar -xz -C /home/runner/clang -f "clang.tar"
