name: Test CLANG

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: kernel/sdm845
        key: main
        restore-keys: |
          main

    - name: Download and extract kernel
      if: steps.kernel-cache.outputs.cache-hit != 'true'
      run: |
        git clone --branch main https://github.com/Andrey0800770/samsung_sdm845-kernel kernel/sdm845        
          
    - name: Set up cache for clang
      id: clang-cache
      uses: actions/cache@v4.2.0
      with:
        path: /home/runner/clang
        key: googleclang-20
        restore-keys: |
          googleclang-20
          
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
       kernel-dir: sdm845
       kernel-branch: test
       config: star2qlte_chn_open_defconfig
       arch: arm64
       path: /home/runner/clang/bin:$BINUTILS:$PATH
       cflags: "CC=clang CROSS_COMPILE=aarch64-linux-gnu-"
       python: python2
       llvm: 1
       anykernel3: true
