name: Test CLANG

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: sdm845
        key: ksu-susfs
        restore-keys: |
          ksu-susfs
          
    - name: Set up cache for clang
      id: clang-cache
      uses: actions/cache@v4.2.0
      with:
        path: /home/runner/clang
        key: googleclang-20
        restore-keys: |
          googleclang-20

    - name: Download and extract kernel
      if: steps.kernel-cache.outputs.cache-hit != 'true'
      run: |
        git clone --branch ksu+susfs https://github.com/Andrey0800770/samsung_sdm845-kernel sdm845
        
    - name: Download and extract clang
      if: steps.clang-cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p /home/runner/clang
        curl -L https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/68e751fd442387fe6dda44199f2b35613bd65803/clang-r547379.tar.gz | tar -xz -C /home/runner/clang
