name: Build mkfs.erofs Static AArch64

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-mkfs-aarch64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout erofs-utils
      uses: actions/checkout@v4
      with:
        repository: erofs/erofs-utils
        
    - name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
        
    - name: Build mkfs.erofs in ARM64 Ubuntu container
      run: |
        docker run --rm --platform=linux/arm64 -v $PWD:/workspace -w /workspace ubuntu:22.04 bash -c '
          set -e
          export DEBIAN_FRONTEND=noninteractive
          
          echo "=== Installing dependencies ==="
          apt-get update
          apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            git \
            wget \
            zlib1g-dev \
            liblz4-dev \
            liblzma-dev \
            uuid-dev \
            libz-dev \
            liblz4-1 \
            liblzma5 \
            libuuid1
          
          echo "=== Installing static libraries ==="
          apt-get install -y \
            zlib1g-dev:arm64 \
            liblz4-dev:arm64 \
            liblzma-dev:arm64 \
            uuid-dev:arm64 || true
          
          echo "=== Building mkfs.erofs ==="
          cd /workspace
          ./autogen.sh
          
          # Try simple build first
          ./configure \
            --enable-lz4 \
            --enable-liblzma \
            --with-uuid \
            --disable-fuse
          
          # Build only mkfs
          make -j$(nproc) -C mkfs
          
          echo "=== Verifying build ==="
          file mkfs/mkfs.erofs
          ls -la mkfs/mkfs.erofs
          
          echo "=== Testing mkfs.erofs ==="
          ./mkfs/mkfs.erofs --version
          
          echo "=== Creating output ==="
          mkdir -p /workspace/output
          cp mkfs/mkfs.erofs /workspace/output/
          
          # Try to make it more static by copying needed libs
          echo "=== Checking dependencies ==="
          ldd mkfs/mkfs.erofs || echo "Already static"
          
          # Strip the binary
          strip /workspace/output/mkfs.erofs
          
          echo "Final binary info:"
          file /workspace/output/mkfs.erofs
          ls -lh /workspace/output/mkfs.erofs
        '
        
    - name: Upload mkfs.erofs binary
      uses: actions/upload-artifact@v4
      with:
        name: mkfs.erofs-aarch64-static
        path: output/
        retention-days: 30
        
    - name: Create release (on tags)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: output/*
        name: "mkfs.erofs AArch64 Static ${{ github.ref_name }}"
        body: |
          ## mkfs.erofs AArch64 Static Binary
          
          - **Architecture:** aarch64 (ARM64)
          - **Type:** Static binary (no dependencies)
          - **Compatible with:** Linux ARM64, Android (Termux), etc.
          - **Built from:** erofs-utils repository
          
          ### Usage
          ```bash
          chmod +x mkfs.erofs
          ./mkfs.erofs --help
          ./mkfs.erofs -zlz4hc output.erofs input_directory/
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
