name: Build mkfs.erofs Static AArch64
jobs:
  build-mkfs-aarch64:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout erofs-utils
      uses: actions/checkout@v4
      with:
        repository: erofs/erofs-utils
        ref: master
        
    - name: Set up QEMU for multi-arch builds
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
        
    - name: Build mkfs.erofs in ARM64 Ubuntu container
      run: |
        docker run --rm --platform=linux/arm64 -v $PWD:/workspace -w /workspace ubuntu:22.04 bash -c '
          set -e
          export DEBIAN_FRONTEND=noninteractive
          
          echo "=== Installing dependencies ==="
          apt-get update
          apt-get install -y \
            build-essential \
            autoconf \
            automake \
            libtool \
            pkg-config \
            git \
            wget \
            zlib1g-dev \
            liblz4-dev \
            liblzma-dev \
            uuid-dev \
            libfuse-dev
          
          echo "=== Building erofs-utils ==="
          cd /workspace
          ./autogen.sh
          
          # Configure with static linking flags
          ./configure \
            --enable-lz4 \
            --enable-lzma \
            --with-uuid \
            --disable-fuse \
            --disable-shared \
            --enable-static \
            LDFLAGS="-static" \
            CFLAGS="-static"
          
          echo "=== Building all components (lib first, then mkfs) ==="
          make -j$(nproc)
          
          echo "=== Verifying build ==="
          file mkfs/mkfs.erofs
          ls -la mkfs/mkfs.erofs
          
          echo "=== Testing mkfs.erofs ==="
          ./mkfs/mkfs.erofs --version || echo "Version check failed, but binary exists"
          
          echo "=== Creating output directory ==="
          mkdir -p /workspace/output
          cp mkfs/mkfs.erofs /workspace/output/
          
          echo "=== Checking dependencies ==="
          ldd mkfs/mkfs.erofs || echo "Static binary - no dynamic dependencies"
          
          # Strip the binary to reduce size
          strip /workspace/output/mkfs.erofs
          
          echo "=== Final binary info ==="
          file /workspace/output/mkfs.erofs
          ls -lh /workspace/output/mkfs.erofs
          
          # Test that it works
          echo "=== Final test ==="
          /workspace/output/mkfs.erofs --help || echo "Help command completed"
        '
        
    - name: Upload mkfs.erofs binary
      uses: actions/upload-artifact@v4
      with:
        name: mkfs.erofs-aarch64-static
        path: output/
        retention-days: 30
        
    - name: Create release (on tags)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: output/*
        name: "mkfs.erofs AArch64 Static ${{ github.ref_name }}"
        body: |
          ## mkfs.erofs AArch64 Static Binary
          
          - **Architecture:** aarch64 (ARM64)
          - **Type:** Static binary (minimal dependencies)
          - **Compatible with:** Linux ARM64, Android (Termux), etc.
          - **Built from:** erofs-utils repository
          
          ### Usage
          ```bash
          chmod +x mkfs.erofs
          ./mkfs.erofs --help
          ./mkfs.erofs -zlz4hc output.erofs input_directory/
          ```
          
          ### Features
          - LZ4 compression support
          - LZMA compression support  
          - UUID support
          - Optimized for ARM64 architecture
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
