name: Build Kernel DEV
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: KSU
          config: star2qlte_chn_open_defconfig
          arch: arm64
          gcc64-tar: https://developer.arm.com/-/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz
          path: $HOME/gcc64/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin:$PATH
          make-options: "make -j$(nproc --all) CROSS_COMPILE=aarch64-linux-gnu- O=out ARCH=arm64"
          python: python2
          anykernel3: true
