name: Test CLANG

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: sdm845
        key: ksu-susfs
        restore-keys: |
          ksu-susfs

    - name: Download and extract kernel
      if: steps.kernel-cache.outputs.cache-hit != 'true'
      run: |
        git clone --branch ksu+susfs https://github.com/Andrey0800770/samsung_sdm845-kernel sdm845
        pwd
