name: erofs-utils ARM64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04-arm64

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Instalar dependências de build
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf \
          automake \
          libtool \
          pkg-config \
          libuuid-dev \
          liblz4-dev \
          liblzma-dev \
          libzstd-dev \
          zlib1g-dev \
          libfuse-dev

    - name: Configurar e compilar erofs-utils
      run: |
        ./autogen.sh
        ./configure --host=aarch64-linux-gnu --enable-static --without-uuid
        make -j$(nproc)

    - name: Criar diretório de artefatos
      run: |
        mkdir -p build/artifacts

    - name: Empacotar os binários
      run: |
        make install DESTDIR=$(pwd)/build/artifacts

    - name: Fazer upload dos artefatos
      uses: actions/upload-artifact@v4
      with:
        name: erofs-utils-aarch64
        path: build/artifacts/
