name: Test CLANG

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: sdm845
        key: ksu-susfs
        restore-keys: |
          ksu-susfs
          
    - name: Set up cache for clang
      id: clang-cache
      uses: actions/cache@v4.2.0
      with:
        path: /home/runner/clang
        key: googleclang-20
        restore-keys: |
          googleclang-20
          
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
       kernel-dir: sdm845
       kernel-branch: test
       config: star2qlte_chn_open_defconfig
       arch: arm64
       gcc64-tar: https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu.tar.xz
       path: /home/runner/clang/bin:$PATH
       cflags: "--target=aarch64-linux-gnueabi CC=clang CROSS_COMPILE=aarch64-linux-gnu- LLVM=1 AS=$HOME/gcc64/arm-gnu-toolchain-14.2.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-as"
       python: python2
       anykernel3: true
