name: Test CLANG

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.0

    - name: Set up cache for kernel
      id: kernel-cache
      uses: actions/cache@v4.2.0
      with:
        path: sdm845
        key: ksu-susfs
        restore-keys: |
          ksu-susfs
          
    - name: Set up cache for clang
      id: clang-cache
      uses: actions/cache@v4.2.0
      with:
        path: /home/runner/clang
        key: googleclang-20
        restore-keys: |
          googleclang-20
          
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
       kernel-dir: sdm845
       kernel-branch: ksu+susfs
       config: star2qlte_chn_open_defconfig
       arch: arm64
       path: /home/runner/clang/bin:$PATH
       cflags: "CC=clang CROSS_COMPILE=x86_64-unknown-linux-gnu- AS=/home/runner/clang/bin/llvm-as"
       python: python2
       anykernel3: true
