name: Build test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo tee /etc/apt/sources.list > /dev/null <<EOF
          deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse
          deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse
          deb http://security.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse
          EOF
          sudo apt-get update -y
          sudo apt-get install -y git wget make python3 build-essential zip apksigner clang unzip
          git clone --recursive https://github.com/VDavid003/sm64-port-android-base
          cd sm64-port-android-base
          wget -O Super_Mario_64_USA.zip https://myrient.erista.me/files/No-Intro/Nintendo%20-%20Nintendo%2064%20%28BigEndian%29/Super%20Mario%2064%20%28USA%29.zip
          unzip Super_Mario_64_USA.zip -d .
          mv "Super Mario 64 (USA).z64" ./app/jni/src/baserom.us.z64
          ./getSDL.sh

      - name: Build
        run: |
          ls
          cd ./sm64-port-android-base/app/jni/src
          make -j$(nproc --all)
          cd ../../..
          ./gradlew assembleDebug

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: mario
          path: ./app/build/outputs/apk/debug/*
