name: Zyc Clang
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: Andrey0800770/kernel_build_action@main
      with:
          kernel-url: https://github.com/Andrey0800770/samsung_sdm845-kernel
          kernel-dir: sdm845
          kernel-branch: dev
          config: star2qlte_chn_open_defconfig
          arch: arm64
          clang-tar: https://github.com/ZyCromerZ/Clang/releases/download/21.0.0git-20250626-release/Clang-21.0.0git-20250626.tar.gz
          path: $CLANG:$PATH
          cflags: "CC=clang LLVM=1 CROSS_COMPILE=aarch64-linux-gnu- -fno-builtin"
          python: python2
          anykernel3: true
          extra-version: -dev
